#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if ! npm run format; then
  echo "Error: Code formatting failed. Please fix the issues before committing."
  exit 1
fi

if ! npx prettier --write .; then
  echo "Error: Linting failed. Please fix the issues before committing."
  exit 1
fi

if ! npm run lint; then
  echo "Error: Code linting failed. Please fix the issues before committing."
  exit 1
fi

git pull origin main
